Fix typos in ISSUE_TEMPLATE
tldr-pages/tldr-node-client pull request #356
Opened 2021-05-25 03:54 UTC by navarroaxel

## Description
Please explain the changes you made here.

## Checklist

Please review this checklist before submitting a pull request.

- [ ] Code compiles correctly
- [ ] Created tests, if possible
- [x] All tests passing (`npm run test:all`)
- [x] Extended the README / documentation, if necessary

2021-05-25 06:39 UTC, owenvoke approved these changes
My poor English being changed to American English. 😭

Looks fine for consistency, but this technically isn't a typo. 👍🏻

2021-05-25 12:13 UTC, navarroaxel commented
> Looks fine for consistency, but this technically isn't a typo. 👍🏻

@owenvoke I always forget how to spell behavior and the spell checker shown this as an error. 😁

2021-05-25 12:28 UTC, bl-ue requested changes

2021-05-25 12:28 UTC, bl-ue commented on .github/ISSUE_TEMPLATE.md
> +- Node.js version (node --version)
```suggestion
- Node.js version (`node --version`)
```

2021-05-25 12:28 UTC, bl-ue commented on .github/ISSUE_TEMPLATE.md
> +- tldr-node-client version (tldr --version)
```suggestion
- tldr-node-client version (`tldr --version`) 
```

2021-05-28 20:23 UTC, vladimyr approved these changes

2021-05-28 20:23 UTC, merged